apiVersion: skaffold/v1alpha2
kind: Config
build:
  tagPolicy:
    envTemplate:
      template: "{{.DOCKER_REGISTRY}}/jstrachan/bdd-test-angular-io-quickstart-1530532896:{{.VERSION}}"
  artifacts:
  - imageName: changeme
    workspace: .
    docker: {}
  local: {}
deploy:
  kubectl:
    manifests:
profiles:
- name: dev
  build:
    tagPolicy:
      envTemplate:
        template: "{{.DOCKER_REGISTRY}}/jstrachan/bdd-test-angular-io-quickstart-1530532896:{{.DIGEST_HEX}}"
    artifacts:
    - docker: {}
    local: {}
  deploy:
    helm:
      releases:
      - name: bdd-test-angular-io-quickstart-1530532896
        chartPath: charts/bdd-test-angular-io-quickstart-1530532896
        setValueTemplates:
          image.repository: "{{.DOCKER_REGISTRY}}/jstrachan/bdd-test-angular-io-quickstart-1530532896"
          image.tag: "{{.TAG}}"
