apiVersion: v1
description: A Helm chart for Kubernetes
icon: https://raw.githubusercontent.com/jenkins-x/jenkins-x-platform/d273e09/images/nodejs.png
name: bdd-test-angular-io-quickstart-1530532896
version: 0.1.0-SNAPSHOT
